# Generated by Django 4.0.3 on 2022-07-21 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='id',
        ),
        migrations.AddField(
            model_name='song',
            name='song_id',
            field=models.AutoField(default='None', primary_key=True, serialize=False),
        ),
    ]
