# Generated by Django 4.0.3 on 2022-07-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0002_remove_song_id_song_song_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_id',
            field=models.AutoField(default='1', primary_key=True, serialize=False),
        ),
    ]
